In [1]:
import numpy as np

In [2]:
import pandas as pd

In [7]:
weather_df = pd.read_excel("6-weather.xlsx")  #biz buraya bir excel dosyası attık zaten aynı dosyanın ıcınde görebilirsin bunu nasıl şu an
                                              #burada açacağımızı öğrendik excel formatında açtık şimdilik sonra onu weather_df olaraktan
                                              #kaydettik

In [8]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [10]:
weather_df.head()      #data tablosunun başındaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [11]:
weather_df.tail()     #data tablomuzun sonundaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [13]:
##BU ÜSTTEKİLERİ YAPMA NEDENİMİZ DATA TABLOMUZ 10 BİN SATIR OLSA NE YAPIYOR DİYE BAKMAK ICIN BÖYLE CALISITRIRIZ

In [15]:
weather_df.info()   #bize infoları veriyor 4 sütun var diyor 9 tane boş olmayan satır var diyor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [18]:
weather_df.describe()   #data neye benziyor bana bunu anlat çok satır varsa tüm datayı ele alamayız ondan genel tabloya bakmamız gerekebilir

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [19]:
weather_df.count()  #kaç data var data tipi ne

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [21]:
weather_df.isna()     #boş data var mı diye bakarız burada

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False