In [1]:
import numpy as np

In [2]:
import pandas as pd

In [7]:
weather_df = pd.read_excel("6-weather.xlsx")  #biz buraya bir excel dosyası attık zaten aynı dosyanın ıcınde görebilirsin bunu nasıl şu an
                                              #burada açacağımızı öğrendik excel formatında açtık şimdilik sonra onu weather_df olaraktan
                                              #kaydettik

In [8]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [10]:
weather_df.head()      #data tablosunun başındaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [11]:
weather_df.tail()     #data tablomuzun sonundaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [13]:
##BU ÜSTTEKİLERİ YAPMA NEDENİMİZ DATA TABLOMUZ 10 BİN SATIR OLSA NE YAPIYOR DİYE BAKMAK ICIN BÖYLE CALISITRIRIZ

In [15]:
weather_df.info()   #bize infoları veriyor 4 sütun var diyor 9 tane boş olmayan satır var diyor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [18]:
weather_df.describe()   #data neye benziyor bana bunu anlat çok satır varsa tüm datayı ele alamayız ondan genel tabloya bakmamız gerekebilir

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [19]:
weather_df.count()  #kaç data var data tipi ne

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [21]:
weather_df.isna()     #boş data var mı diye bakarız burada

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

WORKING WITH MISSING DATA

In [22]:
weather_na_df = pd.read_excel("6-weatherna.xlsx")  #diğer eksik datalı excel dosyasını içeri çektik

In [24]:
weather_na_df                                      #gördüğün gibi eksik kısımlar var Nan olan

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [26]:
weather_na_df.isna()   #bu sefer boş olanlar oldugundan truelar var

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [28]:
weather_na_df.describe()   #nan olmasını bunu yapamayacağımız anlamına gelmez elimizdekilerle bunu yapabiliriz

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [31]:
weather_na_df["Paris"].count()   #spesifik mesela countu sadece paris veya amsterdam icin calıstırabiliriz mesela pariste 
                                 #6 data var amsterdamda 8 data var gibi

np.int64(6)

In [32]:
weather_na_df["Amsterdam"].count()

np.int64(8)

In [34]:
weather_na_df["Amsterdam"].isna()   #aynı şekilde sadece paris icin isna çalıştırarak missing dataları görebiliriz

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: Amsterdam, dtype: bool

In [37]:
weather_na_df.dropna()  #9 datadan 4 e düştü nan olan satırları sildi direkt 1 inde bile varsa

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [40]:
weather_na_df.dropna(axis=1) #sütunun icinde boş varsa sil dedik satır kalmadı axis=1 sütuna bak demek

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [41]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [44]:
weather_na_df.drop("Paris",axis=1)  #paris sütununu düşürdüm mesela sadece

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [46]:
weather_na_df.fillna(20)      #olmayan değerleri Nan olanlar 20 ile doldur dedım

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [48]:
weather_na_df.mean()    #sütunların ortalamasını aldık burada

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [50]:
weather_na_df.median()  #burada da sütunların medianını aldı

Istanbul     21.5
New York     13.5
Amsterdam    15.5
Paris        15.0
dtype: float64

In [57]:
weather_na_df.fillna(weather_na_df.mean())     #boş olan yerleri mean ile doldurdur dedik AMA
                                               #DİKKAT hepsine aynı ortalamayı koymuyor kendi sütunlarının ortalamasını koyuyor
                                               #aşağıdaki yazdıklarımı da koyabilirim mesela .max .min mantıklı degılde yine de yapılabilir bil

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [58]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [59]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64