In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
weather_df = pd.read_excel("6-weather.xlsx")  #biz buraya bir excel dosyası attık zaten aynı dosyanın ıcınde görebilirsin bunu nasıl şu an
                                              #burada açacağımızı öğrendik excel formatında açtık şimdilik sonra onu weather_df olaraktan
                                              #kaydettik

In [4]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [5]:
weather_df.head()      #data tablosunun başındaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [6]:
weather_df.tail()     #data tablomuzun sonundaki 5 tane datayı getirir

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [7]:
##BU ÜSTTEKİLERİ YAPMA NEDENİMİZ DATA TABLOMUZ 10 BİN SATIR OLSA NE YAPIYOR DİYE BAKMAK ICIN BÖYLE CALISITRIRIZ

In [8]:
weather_df.info()   #bize infoları veriyor 4 sütun var diyor 9 tane boş olmayan satır var diyor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [9]:
weather_df.describe()   #data neye benziyor bana bunu anlat çok satır varsa tüm datayı ele alamayız ondan genel tabloya bakmamız gerekebilir

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [10]:
weather_df.count()  #kaç data var data tipi ne

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [11]:
weather_df.isna()     #boş data var mı diye bakarız burada

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

WORKING WITH MISSING DATA

In [12]:
weather_na_df = pd.read_excel("6-weatherna.xlsx")  #diğer eksik datalı excel dosyasını içeri çektik

In [13]:
weather_na_df                                      #gördüğün gibi eksik kısımlar var Nan olan

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [14]:
weather_na_df.isna()   #bu sefer boş olanlar oldugundan truelar var

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [15]:
weather_na_df.describe()   #nan olmasını bunu yapamayacağımız anlamına gelmez elimizdekilerle bunu yapabiliriz

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [16]:
weather_na_df["Paris"].count()   #spesifik mesela countu sadece paris veya amsterdam icin calıstırabiliriz mesela pariste 
                                 #6 data var amsterdamda 8 data var gibi

np.int64(6)

In [17]:
weather_na_df["Amsterdam"].count()

np.int64(8)

In [18]:
weather_na_df["Amsterdam"].isna()   #aynı şekilde sadece paris icin isna çalıştırarak missing dataları görebiliriz

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: Amsterdam, dtype: bool

In [19]:
weather_na_df.dropna()  #9 datadan 4 e düştü nan olan satırları sildi direkt 1 inde bile varsa

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [20]:
weather_na_df.dropna(axis=1) #sütunun icinde boş varsa sil dedik satır kalmadı axis=1 sütuna bak demek

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [22]:
weather_na_df.drop("Paris",axis=1)  #paris sütununu düşürdüm mesela sadece

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [23]:
weather_na_df.fillna(20)      #olmayan değerleri Nan olanlar 20 ile doldur dedım

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [24]:
weather_na_df.mean()    #sütunların ortalamasını aldık burada

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [25]:
weather_na_df.median()  #burada da sütunların medianını aldı

Istanbul     21.5
New York     13.5
Amsterdam    15.5
Paris        15.0
dtype: float64

In [26]:
weather_na_df.fillna(weather_na_df.mean())     #boş olan yerleri mean ile doldurdur dedik AMA
                                               #DİKKAT hepsine aynı ortalamayı koymuyor kendi sütunlarının ortalamasını koyuyor
                                               #aşağıdaki yazdıklarımı da koyabilirim mesela .max .min mantıklı degılde yine de yapılabilir bil

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [27]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [28]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64

GROUP BY

In [33]:
df = pd.read_csv("6-employee.csv")

In [35]:
df      #veri çoğaldı bir şeyleri seçebilmek zorlaştı

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York

In [37]:
df.describe()   #ortalamasını alabileceği şeylerin ortalamasını aldı falan sayısal işlemler yapabildiği

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [39]:
#df.mean() bunu çalıştırmaya calısırsak hata verir cünkü stringler var verilerin icinde

In [41]:
df["Salary"].mean()  #salary sütunu sayısal değerler içerdiği icin oldu

np.float64(78344.5)

In [44]:
df[["Salary","Experience"]].mean()   #yine ikisininde ortalaması alınabileceğinden birlikte aldıttırdık

Salary        78344.50
Experience        7.06
dtype: float64

In [46]:
df.count() #sayma işleminde hepsini sayabilir

Department    50
Employee      50
Salary        50
Experience    50
City          50
dtype: int64

In [48]:
df[df["Experience"]>6]    #deneyimi 6 dan büyük olanların bütün df listesini getir

   Department Employee  Salary  Experience           City
1       Sales    Emp_2   78555           8         Austin
5          IT    Emp_6   97121          11        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
27         IT   Emp_28   53247          11         Austin
32  Marketing   Emp_33  116807          14  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
47      Sales   Emp_48   78190           7         Austin

In [51]:
df[df["Experience"]>6].count()   #tecrübesi 6 dan büyük olan kaç kişi var sorusunun cevabını verir

Department    30
Employee      30
Salary        30
Experience    30
City          30
dtype: int64

In [53]:
df.head() #df.head() bize DataFrame’in ilk 5 satırını gösteriyor. Yani verinin genel yapısını hızlıca kontrol etmek için kullanılıyor.

  Department Employee  Salary  Experience           City
0  Marketing    Emp_1   53483           1       New York
1      Sales    Emp_2   78555           8         Austin
2    Finance    Emp_3   47159           3         Austin
3      Sales    Emp_4  110077           3  San Francisco
4      Sales    Emp_5   65920           1       New York

In [56]:
df.groupby("Department")

In [57]:
df_grouped = df.groupby("Department")

In [61]:
df_grouped.count() #departmanlara göre grupladık ve departmanlara göre dağılışlarına baktık

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [63]:
df_grouped.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

In [65]:
df_grouped["Salary"].mean()   #departmanlara göre maaşları bulduk

Department
Finance      90552.700000
HR           76182.571429
IT           63381.600000
Marketing    79555.000000
Sales        81038.900000
Name: Salary, dtype: float64

In [66]:
df_city = df.groupby("City")

In [68]:
df_city.count()

               Department  Employee  Salary  Experience
City
Austin                 13        13      13          13
Chicago                11        11      11          11
New York               15        15      15          15
San Francisco          11        11      11          11

In [69]:
df_city["Salary"]

In [70]:
df_city["Salary"].mean()

City
Austin           81216.000000
Chicago          76869.363636
New York         70484.133333
San Francisco    87144.727273
Name: Salary, dtype: float64