In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("8-apply_function_data.csv")

In [5]:
df   #uzun bir tablo olduğundan hepsini göstermedi

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [6]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [7]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [8]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [10]:
df.info()    #hepsi sütunların 100 ve non-null cıktı yani boş bırakılmış bir alan yok

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

datayı tam göremediğimiz için datayı anlamak için üstteki 4 ünü çalıştırıp bi inceleriz

In [13]:
df.columns      #daha da uzun bir veri olsaydı o zaman sütun adlarına bakmak icin bunu yapabilirdik

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [15]:
df[1:20]    #ilk 20 rowunu görmek için slicing işlemini yapabiliriz mesela

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [21]:
def salary_category(salary):
    if salary < 50000:
        return "low"
    elif 50000 <= salary < 80000:
        return "medium"
    else:
        return "high"

In [23]:
df["Salary"].apply(salary_category)    #benim df imi Salary isine bakaraktan salary_category fonksiyonuna göre sınıflandır

0       high
1     medium
2        low
3     medium
4       high
       ...
95      high
96      high
97      high
98       low
99    medium
Name: Salary, Length: 100, dtype: object

In [26]:
df["Salary_Category"] = df["Salary"].apply(salary_category)   #burada df tablosuna şu isimle ekle yeni oluştuduğumuz sınıflandırmayı dedik

In [27]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,high
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,high
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high
96,97,Emp_97,Sales,100467,22,2,high
97,98,Emp_98,IT,82662,23,3,high
98,99,Emp_99,IT,42688,22,1,low
99,100,Emp_100,HR,55342,14,3,medium

şimdi hoca benden şunu isityor eğerki çalışanın experience'ı 10 dan fazla ise performance_score'u 1 arttırıp tabloya ekleyeceğim

In [49]:
def performanceScore(ex):
    if ex>10:
        return 1
    else:
        return 0

In [50]:
df["Experience"].apply(performanceScore)

0     0
1     1
2     0
3     1
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Experience, Length: 100, dtype: int64

In [52]:
df["New_Score"] = df["Experience"].apply(performanceScore)

In [53]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Score
0,1,Emp_1,Marketing,82251,6,5,high,0
1,2,Emp_2,Sales,52662,24,3,medium,1
2,3,Emp_3,Finance,38392,5,3,low,0
3,4,Emp_4,Sales,60535,20,3,medium,1
4,5,Emp_5,Sales,108603,2,2,high,0
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1
96,97,Emp_97,Sales,100467,22,2,high,1
97,98,Emp_98,IT,82662,23,3,high,1
98,99,Emp_99,IT,42688,22,1,low,1
99,100,Emp_100,HR,55342,14,3,medium,1

In [56]:
df["New_Score"] = df["Performance_Score"] + df["New_Score"]

In [57]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Score
0,1,Emp_1,Marketing,82251,6,5,high,5
1,2,Emp_2,Sales,52662,24,3,medium,5
2,3,Emp_3,Finance,38392,5,3,low,3
3,4,Emp_4,Sales,60535,20,3,medium,5
4,5,Emp_5,Sales,108603,2,2,high,2
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,6
96,97,Emp_97,Sales,100467,22,2,high,4
97,98,Emp_98,IT,82662,23,3,high,5
98,99,Emp_99,IT,42688,22,1,low,3
99,100,Emp_100,HR,55342,14,3,medium,5

In [61]:
def adjust_new(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] +1
    else:
        return row["Performance_Score"]

In [62]:
df["Adjusted_Score"] = df.apply(adjust_new , axis = 1)

In [63]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,New_Score,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,high,5,5
1,2,Emp_2,Sales,52662,24,3,medium,5,4
2,3,Emp_3,Finance,38392,5,3,low,3,3
3,4,Emp_4,Sales,60535,20,3,medium,5,4
4,5,Emp_5,Sales,108603,2,2,high,2,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,6,5
96,97,Emp_97,Sales,100467,22,2,high,4,3
97,98,Emp_98,IT,82662,23,3,high,5,4
98,99,Emp_99,IT,42688,22,1,low,3,2
99,100,Emp_100,HR,55342,14,3,medium,5,4