In [170]:
import pandas as pd

In [171]:
import numpy as np

In [172]:
data = np.random.randn(4,3)    #4X3 boyutunda bize data oluşturdu burada

In [173]:
data

array([[ 0.43220649, -0.66872297, -0.29587319],
       [-0.61555149, -2.56980224,  0.70812378],
       [-1.34749286, -2.07581221,  0.18105452],
       [-0.473163  ,  0.50202632,  0.14130955]])

data_frame = pd.Series(data) eğer böyle yaparsak hata olur çünkü seriesler tek sütunlar icin geçerli

In [174]:
data_frame = pd.DataFrame(data)  #data frame ama çok boyutlularda kullanılır

In [175]:
data_frame                       #Görüldüğü üzere excel gibi yerleştirdi dataları

          0         1         2
0  0.432206 -0.668723 -0.295873
1 -0.615551 -2.569802  0.708124
2 -1.347493 -2.075812  0.181055
3 -0.473163  0.502026  0.141310

In [176]:
type(data_frame)

pandas.core.frame.DataFrame

In [177]:
data_frame[0]  #tabi ki dataframelerde de index mantığı var

0    0.432206
1   -0.615551
2   -1.347493
3   -0.473163
Name: 0, dtype: float64

In [178]:
type(data_frame[0])    #gördüğün gibi sonda series yazıyor dataframde serieslerin birleşiminden oluşur

pandas.core.series.Series

In [179]:
new_df = pd.DataFrame(data, index = ["Omer", "Buse", "Bekir" , "Elif"], columns=["Salary", "Age" , "Seniorty"])

In [180]:
new_df

         Salary       Age  Seniorty
Omer   0.432206 -0.668723 -0.295873
Buse  -0.615551 -2.569802  0.708124
Bekir -1.347493 -2.075812  0.181055
Elif  -0.473163  0.502026  0.141310

In [181]:
new_df["Salary"]      #sütunları getirebiliyoruz böyle

Omer     0.432206
Buse    -0.615551
Bekir   -1.347493
Elif    -0.473163
Name: Salary, dtype: float64

In [182]:
new_df[["Age","Salary"]]   #istediğimiz iki sütunu çağırdık ama liste içinde liste gibi yazaraktan

            Age    Salary
Omer  -0.668723  0.432206
Buse  -2.569802 -0.615551
Bekir -2.075812 -1.347493
Elif   0.502026 -0.473163

new_df["Omer"] SATIRLAR BÖYLE ALINMAZ BU SÜTUNLARI ALMA TAKTİĞİ

In [183]:
new_df.loc["Omer"] #EĞER SATIRI ALMAK İSTİYORSAK .loc methodu ile alırız

Salary      0.432206
Age        -0.668723
Seniorty   -0.295873
Name: Omer, dtype: float64

In [184]:
new_df.iloc[0]        #locationa göre 0. indexi getir mesela satır kısmında sayılar olsa böyle alacaktık

Salary      0.432206
Age        -0.668723
Seniorty   -0.295873
Name: Omer, dtype: float64

In [185]:
new_df.iloc[1]      #bu seferde 1.satırı aldık busenin bilgileri geldi mesela

Salary     -0.615551
Age        -2.569802
Seniorty    0.708124
Name: Buse, dtype: float64

In [186]:
new_df.iloc[:,2]    #bütün satırları al ama sütun olaraktan sadece 2 yi getir dedik

Omer    -0.295873
Buse     0.708124
Bekir    0.181055
Elif     0.141310
Name: Seniorty, dtype: float64

In [187]:
new_df.iloc[0:3,2]  #satırdan 0 dan 3 e kadar al 3 dahil değil ama sütun olarak 2 yi al

Omer    -0.295873
Buse     0.708124
Bekir    0.181055
Name: Seniorty, dtype: float64

In [188]:
new_df["Age"]      #age sütununu getirir

Omer    -0.668723
Buse    -2.569802
Bekir   -2.075812
Elif     0.502026
Name: Age, dtype: float64

YENİ SÜTUN PEKİ NASIL ATARIZ

In [189]:
new_df["Extra"]=10   #BURADA GÖRÜLDÜĞÜ ÜZERE EXTRA DİYE BİR SÜTUN YOK BUNU EKLEDIK VE ORAYA HEP 10 ATADIK.

In [190]:
new_df

         Salary       Age  Seniorty  Extra
Omer   0.432206 -0.668723 -0.295873     10
Buse  -0.615551 -2.569802  0.708124     10
Bekir -1.347493 -2.075812  0.181055     10
Elif  -0.473163  0.502026  0.141310     10

In [191]:
new_df.drop("Extra",axis=1)

         Salary       Age  Seniorty
Omer   0.432206 -0.668723 -0.295873
Buse  -0.615551 -2.569802  0.708124
Bekir -1.347493 -2.075812  0.181055
Elif  -0.473163  0.502026  0.141310

In [192]:
new_df     #drope yapsakta geçmedi bunun icin inplace diyip true ya eşitlememiz lazım

         Salary       Age  Seniorty  Extra
Omer   0.432206 -0.668723 -0.295873     10
Buse  -0.615551 -2.569802  0.708124     10
Bekir -1.347493 -2.075812  0.181055     10
Elif  -0.473163  0.502026  0.141310     10

In [193]:
new_df.drop("Extra", axis=1 ,inplace=True)

In [194]:
new_df      #GÖRÜLDÜĞÜ ÜZERE BU SEFER DEĞİŞTİ

         Salary       Age  Seniorty
Omer   0.432206 -0.668723 -0.295873
Buse  -0.615551 -2.569802  0.708124
Bekir -1.347493 -2.075812  0.181055
Elif  -0.473163  0.502026  0.141310

In [195]:
new_df["Elif"]=10

In [196]:
new_df      #HEM SATIRDA HEM SÜTUNDA ELİF OLDU NASIL BİR SIKINTI OLACAK AŞAĞIDA GÖRELİM

         Salary       Age  Seniorty  Elif
Omer   0.432206 -0.668723 -0.295873    10
Buse  -0.615551 -2.569802  0.708124    10
Bekir -1.347493 -2.075812  0.181055    10
Elif  -0.473163  0.502026  0.141310    10

In [197]:
new_df.drop("Elif")   #Görldüğü üzere burada öncelikli olaraktan satırdaki elifi sildi"

         Salary       Age  Seniorty  Elif
Omer   0.432206 -0.668723 -0.295873    10
Buse  -0.615551 -2.569802  0.708124    10
Bekir -1.347493 -2.075812  0.181055    10

In [198]:
new_df

         Salary       Age  Seniorty  Elif
Omer   0.432206 -0.668723 -0.295873    10
Buse  -0.615551 -2.569802  0.708124    10
Bekir -1.347493 -2.075812  0.181055    10
Elif  -0.473163  0.502026  0.141310    10

In [199]:
new_df.drop("Elif",axis=1)    #axis 1 yazıp Elifi droplarsak ama o zaman sütun gider

         Salary       Age  Seniorty
Omer   0.432206 -0.668723 -0.295873
Buse  -0.615551 -2.569802  0.708124
Bekir -1.347493 -2.075812  0.181055
Elif  -0.473163  0.502026  0.141310

In [200]:
new_df.loc["Bekir"]   #bekirin değerlerini aldık burada

Salary      -1.347493
Age         -2.075812
Seniorty     0.181055
Elif        10.000000
Name: Bekir, dtype: float64

In [201]:
new_df.loc["Bekir"]["Salary"]    #eğer spesifik olarak birinin maaşını istiyorsak böyle yazabiliriz

np.float64(-1.3474928576610012)

In [202]:
new_df.loc["Bekir","Salary"]     #bu şekilde de bir yazım yaparsak spesifik birinin maaşını çekebiliriz

np.float64(-1.3474928576610012)

In [203]:
new_df.loc["Bekir","Salary"] =100.000   #burada da bekirin maaşını değiştirdik

In [204]:
new_df

           Salary       Age  Seniorty  Elif
Omer     0.432206 -0.668723 -0.295873    10
Buse    -0.615551 -2.569802  0.708124    10
Bekir  100.000000 -2.075812  0.181055    10
Elif    -0.473163  0.502026  0.141310    10

In [205]:
new_df > 0

       Salary    Age  Seniorty  Elif
Omer     True  False     False  True
Buse    False  False      True  True
Bekir    True  False      True  True
Elif    False   True      True  True

In [206]:
boolean_frame = new_df > 0

In [207]:
new_df[boolean_frame]    #bu 0 dan büyükleri göster dedıgımız şeyide dataframe verirsek sadece 0 dan
                         #büyükleri gösterir diğerlerini non yani yok olaraktan alır

           Salary       Age  Seniorty  Elif
Omer     0.432206       NaN       NaN    10
Buse          NaN       NaN  0.708124    10
Bekir  100.000000       NaN  0.181055    10
Elif          NaN  0.502026  0.141310    10

In [208]:
new_df[new_df["Salary"] > 1] #maaş kolonu 1 den büyük olanları getir dedı 1 kişinin öyle oldugundan bunu getirdi

       Salary       Age  Seniorty  Elif
Bekir   100.0 -2.075812  0.181055    10

In [209]:
new_df[new_df > 0]     #aynı şeyi gösterdi cünkü direkt içiçe koyduk uzatmadık üstte dikkat edersen orada
                       #da uzatmalı bir içiçe koyma var aslında

           Salary       Age  Seniorty  Elif
Omer     0.432206       NaN       NaN    10
Buse          NaN       NaN  0.708124    10
Bekir  100.000000       NaN  0.181055    10
Elif          NaN  0.502026  0.141310    10

In [210]:
new_df.reset_index()   #indexi ayrı bir sütun olaraktan açtı

   index      Salary       Age  Seniorty  Elif
0   Omer    0.432206 -0.668723 -0.295873    10
1   Buse   -0.615551 -2.569802  0.708124    10
2  Bekir  100.000000 -2.075812  0.181055    10
3   Elif   -0.473163  0.502026  0.141310    10

In [211]:
new_df    #new df yine de bozulmadı

           Salary       Age  Seniorty  Elif
Omer     0.432206 -0.668723 -0.295873    10
Buse    -0.615551 -2.569802  0.708124    10
Bekir  100.000000 -2.075812  0.181055    10
Elif    -0.473163  0.502026  0.141310    10

In [212]:
reset_frame = new_df.reset_index()

In [213]:
reset_frame

   index      Salary       Age  Seniorty  Elif
0   Omer    0.432206 -0.668723 -0.295873    10
1   Buse   -0.615551 -2.569802  0.708124    10
2  Bekir  100.000000 -2.075812  0.181055    10
3   Elif   -0.473163  0.502026  0.141310    10

In [214]:
reset_frame.loc[0]    #burada da artık indexler 0 1 2 3 diye olduğu için 0.index dediğimizde omeri getirdi

index           Omer
Salary      0.432206
Age        -0.668723
Seniorty   -0.295873
Elif              10
Name: 0, dtype: object

In [215]:
new_indices =["ati","zey","yag","mur"]

In [216]:
new_df["NewIndex"]=new_indices

In [217]:
new_df       #yeni sütunun icine yeni indexleri yerleştirdik

           Salary       Age  Seniorty  Elif NewIndex
Omer     0.432206 -0.668723 -0.295873    10      ati
Buse    -0.615551 -2.569802  0.708124    10      zey
Bekir  100.000000 -2.075812  0.181055    10      yag
Elif    -0.473163  0.502026  0.141310    10      mur

In [218]:
new_df.set_index("NewIndex", inplace=True)    #yeni indexlerini newindex sütunundakiler yaptık

In [219]:
new_df

              Salary       Age  Seniorty  Elif
NewIndex
ati         0.432206 -0.668723 -0.295873    10
zey        -0.615551 -2.569802  0.708124    10
yag       100.000000 -2.075812  0.181055    10
mur        -0.473163  0.502026  0.141310    10

In [220]:
new_df.loc["ati"]         #artık indexler bu oldugundan böylede gelir

Salary       0.432206
Age         -0.668723
Seniorty    -0.295873
Elif        10.000000
Name: ati, dtype: float64

YA MULTİ İNDEXLİ OLURSA

In [239]:
first_index = ["Simpson","Simpson","Simpson","South Park", "South Park","South Park"]

In [240]:
inner_index = ["Homer", "Bart", "Marge" , "Cartman" , "Kenny" , "Kyle"]

In [241]:
zipped_index = list(zip(first_index, inner_index))

In [242]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [243]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [244]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [247]:
sample_values = np.ones((6,2))

In [248]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns = ["Age","Salary"])

In [250]:
big_df   #GÖRDÜĞÜN ÜZERE ALTTA 2 INDEX OLDU ARTIK

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [251]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [253]:
#big_df.loc["Homer"]  BUNU BÖYLE YAZARSAK GETİRMEZ ÇÜNKÜ BURADA MULTIINDEX VARDIR

In [255]:
big_df.loc["Simpson", "Homer"]  #bak artık homer ı getirdi

Age       1.0
Salary    1.0
Name: (Simpson, Homer), dtype: float64